# Welcome to JekyllMe
#
# This config file includes settings that affect your whole site,
# which you set up once and will rarely need to edit after that.
# This file is not reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JekyllMe
avatar_path: "/img/avatar.svg" # The location of your homepage avatar
description: > # this means to ignore newlines until "baseurl:"
  your free personal website
baseurl: "/JekyllMe" # the subpath of your site, e.g. /blog
url: "https://damianeoloan.github.io" # the base hostname & protocol for your site
resume: true
permalink: /:title/

# Social profiles
twitter_username: damianeoloan # this will appear on your homepage
linkedin_path: "https://www.linkedin.com/in/damian-o-loan-b6626234" # this will appear on your homepage
github_username: damianeoloan # this will appear on your homepage
email: damianoloan0@gmail.com # To receive emails from the contact form, you'll need to submit one test email

# Build settings
markdown: kramdown

# API keys
api_keys:
  google: "AIzaSyBTrns7kOi-WxTG7d-IrwzApkn4JvlCL5c"

# Gems
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 8
paginate_path: "/blog/page:num/"

# Mentions
jekyll-mentions: https://twitter.com

# Collections
collections:
  portfolio-items:
    title: Portfolio # This will appear on your homepage
    output: true # No pages for each portfolio item

resume-items:
# Resume summary
  name: "John Doe"
  title: "Frontend Developer" # Your job title
  location: "London, UK" # Your current location
  avatar: "/img/avatar.svg"
# Resume languages
  languages: # SVG Flags adapted from https://github.com/lipis/flag-icon-css
  - name: English
    level: Native
    icon: !xml |
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512">
          <defs>
            <clipPath id="a">
              <path fill-opacity=".67" d="M250 0h500v500H250z"/>
            </clipPath>
          </defs>
          <g clip-path="url(#a)" transform="translate(-256) scale(1.024)">
            <g stroke-width="1pt">
              <path fill="#006" d="M0 0h1000.02v500.01H0z"/>
              <path d="M0 0v55.903l888.218 444.11h111.802V444.11L111.802.003H0zm1000.02 0v55.9L111.802 500.01H0v-55.9L888.218 0h111.802z" fill="#fff"/>
              <path d="M416.675 0v500.01h166.67V0h-166.67zM0 166.67v166.67h1000.02V166.67H0z" fill="#fff"/>
              <path d="M0 200.004v100.002h1000.02V200.004H0zM450.01 0v500.01h100V0h-100zM0 500.01l333.34-166.67h74.535L74.535 500.01H0zM0 0l333.34 166.67h-74.535L0 37.27V0zm592.145 166.67L925.485 0h74.535L666.68 166.67h-74.535zm407.875 333.34L666.68 333.34h74.535l258.805 129.403v37.267z" fill="#c00"/>
            </g>
          </g>
        </svg>
  - name: French
    level: Fluent
    icon: !xml |
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 512 512" version="1">
          <g fill-rule="evenodd" stroke-width="1pt">
            <path fill="#fff" d="M0 0h512.005v512H0z"/>
            <path fill="#006" d="M0 0h170.667v512H0z"/>
            <path fill="#c00" d="M341.333 0H512v512H341.333z"/>
          </g>
        </svg>
  - name: Chinese
    level: Professional
    icon: !xml |
        <?xml version="1.0" encoding="UTF-8"?>
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 30 30">
        <defs>
        <path id="s" d="M0,-1 0.587785,0.809017 -0.951057,-0.309017H0.951057L-0.587785,0.809017z" fill="#ffde00"/>
        </defs>
        <rect width="30" height="30" fill="#c00"/>
        <use xlink:href="#s" transform="translate(5,10) scale(3)"/>
        <use xlink:href="#s" transform="translate(10,7) rotate(23.036243)"/>
        <use xlink:href="#s" transform="translate(12,9) rotate(45.869898)"/>
        <use xlink:href="#s" transform="translate(12,12) rotate(69.945396)"/>
        <use xlink:href="#s" transform="translate(10,14) rotate(20.659808)"/>
        </svg>
# Resume skills
  skills:
  - name: Skill 1
    level: 90 # How you score yourself for this skill, expressed as a %
    icon: ""
  - name: Skill 2
    level: 90
    icon: ""
  - name: Skill 3
    level: 80
    icon: ""
  - name: Skill 4
    level: 60
    icon: ""
  - name: Skill 5
    level: 40
    icon: ""
  - name: Skill 6
    level: 30
    icon: ""
  - name: Skill 7
    level: 20
    icon: ""
  experiences:
  - title: A job title
    company: A company name
    address: 1 Random St, Randomville
    coordinates:
      latitude: 40.036730
      longitude: 116.315243
    start-date: 01/2014
    end-date: 01/2016
    details:
      - "Something you achieved in this position"
      - "Something else you achieved in this position"
      - "Something else you achieved in this position"
  - title: Another job title
    company: Another company name
    address: 2 Random Rd, Randomville
    coordinates:
      latitude: 30.189894
      longitude: 120.190178
    start-date: 01/2012
    end-date: 01/2014
    details:
      - "Something you achieved in this position"
      - "Something else you achieved in this position"
      - "Something else you achieved in this position"
  - title: Another job title
    company: Another company name
    address: 3 Random Ave, Randomville
    coordinates:
      latitude: 31.226251
      longitude: 121.449163
    start-date: 01/2010
    end-date: 01/2012
    details:
      - "Something you achieved in this position"
      - "Something you achieved in this position"
      - "Something you achieved in this position"
  qualifications:
    - title: "MA Hons Philosophy"
      awarding-body: "University of Jekyll"
      date: "06/2000"
  interests:
  - name: an interest!
    icon: !xml |
        <?xml version="1.0" encoding="UTF-8"?>
        <svg xmlns="http://www.w3.org/2000/svg" viewbox="0,0,497,470">
          <g stroke-width="20">
            <path d="M140,20C 73,20 20,74 20,140 20,275 156,310 248,443 336,311 477,270 477,140 477,74 423,20 357,20 309,20 267,48 248,89 229,48 188,20 140,20Z" />
          </g>
        </svg>
  - name: a hobby!
    icon: !xml |
        <?xml version="1.0" encoding="UTF-8"?>
        <svg xmlns="http://www.w3.org/2000/svg" viewbox="0,0,497,470">
          <g stroke-width="20">
            <path d="M140,20C 73,20 20,74 20,140 20,275 156,310 248,443 336,311 477,270 477,140 477,74 423,20 357,20 309,20 267,48 248,89 229,48 188,20 140,20Z" />
          </g>
        </svg>
  - name: a passion!
    icon: !xml |
        <?xml version="1.0" encoding="UTF-8"?>
        <svg xmlns="http://www.w3.org/2000/svg" viewbox="0,0,497,470">
          <g stroke-width="20">
            <path d="M140,20C 73,20 20,74 20,140 20,275 156,310 248,443 336,311 477,270 477,140 477,74 423,20 357,20 309,20 267,48 248,89 229,48 188,20 140,20Z" />
          </g>
        </svg>
